name: Snyk Security Scan

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (for JavaScript/TypeScript dependencies)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (if package.json exists)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Snyk Scan
        uses: snyk/actions@v3
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

      - name: Snyk Monitor
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: snyk/actions@v3
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
