      - name: Snyk Monitor
        if: github.ref == 'refs/heads/main'
        uses: snyk/actions@v3
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
